<?php 
include("../../funciones/funciones.php");

$empresa=recoger($_Post['empresa']);
$contratacionalumno=recoger($_Post['contratacionalumno']);
$alumno=recoger($_Post['alumno']);
$curso=recoger($_Post['curso']);
$busqueda=array();
if($empresa==0){
$busqueda[]="empresa";
}
if($contratacionalumno==0){
$busqueda[]="contratacionalumno";
}
if($alumno==0){
$busqueda[]="alumno";
}
if($curso==0){
$busqueda[]="curso";
}
preparar_busqueda("asignaciones",$busqueda);
?>
