<?php 
include("../../funciones/funciones.php");

$nombre=recoger($_Post['nombre']);
$uskera=recoger($_Post['euskera']);
$carnet=recoger($_Post['carnet']);
$abreviatura=recoger($_Post['abreviatura']);
$curso=recoger($_Post['curso']);
$busqueda=array();
if($nombre==0){
$busqueda[]="nombre";
}
if($uskera==0){
    $busqueda[]="euskera";
}
if($carnet==0){
    $busqueda[]="carnet";
}
if($abreviatura==0){
    $busqueda[]="abreviatura";
}
if($curso==0){
    $busqueda[]="curso";
}
preparar_busqueda("alumnos",$busqueda);
?>
