<?php 
include("../../funciones/funciones.php");

$abreviatura=recoger($_Post['abreviatura']);
$denominacion=recoger($_Post['denominacion']);
$ciclo=recoger($_Post['ciclo']);
$tutor=recoger($_Post['tutor']);
$tutorpracticas=recoger($_Post['tutorpracticas']);
$busqueda=array();
if($abreviatura==0){
$busqueda[]="abreviatura";
}
if($denominacion==0){
$busqueda[]="denominacion";
}
if($ciclo==0){
$busqueda[]="ciclo";
}
if($tutor==0){
$busqueda[]="tutor";
}
if($tutorpracticas==0){
$busqueda[]="tutorpracticas";
}
preparar_busqueda("grupos",$busqueda);
?>
