<?php 
include("../../funciones/funciones.php");

$nombre=recoger($_Post['nombre']);
$titularidad=recoger($_Post['titularidad']);
$poblacion=recoger($_Post['poblacion']);
$provincia=recoger($_Post['provincia']);
$convenio=recoger($_Post['convenio']);
$busqueda=array();
if($nombre==0){
$busqueda[]="nombre";
}
if($titularidad==0){
$busqueda[]="titularidad";
}
if($poblacion==0){
$busqueda[]="poblacion";
}
if($provincia==0){
$busqueda[]="provincia";
}
if($convenio==0){
$busqueda[]="convenio";
}
preparar_busqueda("empresas",$busqueda);
?>
